Added R linting via `lintr`

diff --git a/.github/workflows/lint-project.yaml b/.github/workflows/lint-project.yaml
--- a/.github/workflows/lint-project.yaml
+++ b/.github/workflows/lint-project.yaml
@@ -12,31 +12,43 @@ name: Lint project
 
 jobs:
   lint-project:
-    runs-on: macOS-latest
+    runs-on: ubuntu-latest
+    container: rocker/verse
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+    path: /
     steps:
       - uses: actions/checkout@v2
 
-      - uses: r-lib/actions/setup-r@v1
+      # - uses: r-lib/actions/setup-r@v1
 
-      - name: Install lintr
-        run: install.packages("lintr")
-        shell: Rscript {0}
+      - name: Install R dependencies
+        run: |
+          Rscript -e 'install.packages(c("lintr", "magrittr", "stringr"))'
 
       - name: Lint project directory
-        run: Rscript -e 'lintr::lint("README.Rmd")'
-        shell: bash
+        run: |
+          Rscript '.github/lint_r_files.R'
 
-      - uses: actions-ecosystem/action-regex-match@v2
-        id: regex-match
-        name: Check variable names
-        with:
-          text: ${{ github.event.comment.body }}
-          regex: '^( |\t)*(\w|data) *(=|<-).*$'
+      - name: Linting results
+        run: |
+          if [ -f ".github/linting_fail" ]; then
+            echo "Some tests failed"
+            exit 1
+          else
+            echo "All tests passed"
+            exit 0
+          fi
 
-      - uses: actions-ecosystem/action-add-labels@v1
-        if: ${{ steps.regex-match.outputs.match != '' }}
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          labels: ${{ steps.regex-match.outputs.group1 }}
+      # - uses: actions-ecosystem/action-regex-match@v2
+      #   id: regex-match
+      #   name: Check variable names
+      #   with:
+      #     text: ${{ github.event.comment.body }}
+      #     regex: '^( |\t)*(\w|data) *(=|<-).*$'
+      #
+      # - uses: actions-ecosystem/action-add-labels@v1
+      #   if: ${{ steps.regex-match.outputs.match != '' }}
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     labels: ${{ steps.regex-match.outputs.group1 }}
